import { Router } from "express";
import cliente from "./cliente";
import  Cabecera_Factura  from "./Cabecera_Factura";
import  Detalle_Factura  from "./Detalle_Factura";
import  Producto  from "./Producto";
import  Proovedor  from "./Proveedor";
import  Vendedor  from "./Vendedor";
const routes = Router();
routes.use("/Cliente", cliente);
routes.use("/Cabecera_Factura",Cabecera_Factura);
routes.use("/Cliente", cliente);
routes.use("/Detalle_Factura",Detalle_Factura);
routes.use("/Producto",Producto);
routes.use("/Proveedor",Proovedor);
routes.use("/Vendedor",Vendedor);
export default routes;